---
- name: download and untar node_exporter tarball
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v0.15.1/node_exporter-0.15.1.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes

- name: copy systemd config to server
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
  notify:
    - reload systemd
    - restart node_exporter

- name: Flush handlers
  meta: flush_handlers

- name: Ensure node_exporter is enabled and started
  service:
    name: node_exporter
    enabled: yes
    state: started

- name: Wait for node-exporter to be up
  wait_for:
    port: "9100"
    timeout: 20

- name: Check that you can connect to the node-exporter metrics page
  uri:
    url: "http://127.0.0.1:9100/metrics"
    return_content: yes
  register: node_metric_page_result
  always_run: true

- name: Ensure that node-exporter metrics is served by http
  assert:
    that: "'go_gc_duration_seconds' in node_metric_page_result.content"
