---
- hosts: all
  become: true
  roles:
    - role: prometheus-node
      tags: prometheus-node

- hosts: kafka
  become: true
  roles:
    - role: kafka

- hosts: prom
  become: true
  roles:
    - role: prometheus-server
      tags: prometheus-server

- hosts: grafana
  become: true
  roles:
    - role: alertmanager
      tags: alertmanager
