---
- hosts: all
  become: true
  roles:
    - role: prometheus-node
      tags: prometheus-node

- hosts: app
  become: true
  roles:
    - role: app
      tags: app
    - role: jenkins
      tags: jenkins

- hosts: kafka
  become: true
  roles:
    - role: kafka
      tags: kafka

- hosts: prom
  become: true
  roles:
    - role: prometheus-server
      tags: prometheus-server

- hosts: grafana
  become: true
  roles:
    - role: alertmanager
      tags: alertmanager
    - role: grafana
      tags: grafana
