---
- hosts: all
  become: true
  roles:
    - role: prometheus-node
      tags: prometheus-node
    - role: ntp
      tags: ntp

- hosts: kafka
  become: true
  roles:
    - role: kafka

- hosts: prom
  become: true
  roles:
    - role: prometheus-server
      tags: prometheus-server

- hosts: grafana
  become: true
  roles:
    - role: alertmanager
      tags: alertmanager
    - role: grafana
      tags: grafana
