Vagrant.configure(2 ) do |config|

  config.vm.define :app, autostart: true do |app|
    app.vm.box = "centos/7"
    app.vm.hostname = "app"
    app.vm.network "private_network", ip: "192.168.201.10"
  end

  config.vm.define :prom, autostart: true do |prom|
    prom.vm.box = "centos/7"
    prom.vm.hostname = "prom"
    prom.vm.network "private_network", ip: "192.168.201.11"
  end

  config.vm.define :kafka, autostart: true do |kafka|
    kafka.vm.box = "centos/7"
    kafka.vm.hostname = "kafka"
    kafka.vm.network "private_network", ip: "192.168.201.12"
  end

  config.vm.define :grafana, autostart: true do |grafana|
    grafana.vm.box = "centos/7"
    grafana.vm.hostname = "grafana"
    grafana.vm.network "private_network", ip: "192.168.201.13"
  end

end
