---
- name: Install OpenJDK 1.8
  yum:
    name: java-1.8.0-openjdk.x86_64
    state: present

- name: Update profile file with java var
  blockinfile:
    path: /etc/profile
    block: |
      export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk
      export JRE_HOME=/usr/lib/jvm/jre
    insertafter: EOF

- name: Ensure unzip is install
  yum:
    name: unzip
    state: present

- name: Download Apache Kafka
  unarchive:
    src: http://www-us.apache.org/dist/kafka/0.10.2.1/kafka_2.10-0.10.2.1.tgz
    dest: /opt
    remote_src: yes

- name: Download jmx prometheus agent
  get_url:
    url: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.1.0/jmx_prometheus_javaagent-0.1.0.jar
    dest: /opt/kafka_2.10-0.10.2.1/config/jmx_prometheus_javaagent.jar

- name: Copy kafka config
  copy:
    src: kafka.config
    dest: /etc/sysconfig/kafka
  
- name: Copy Kafka yaml prometheus transcript
  copy:
    src: kafka_prometheus.yml
    dest: /opt/kafka_2.10-0.10.2.1/config/kafka_prometheus.yml

- name: Ensure zookeeper systemd file is present
  copy:
    src: zookeeper.service
    dest: /etc/systemd/system/zookeeper.service
  notify:
    - reload systemd
    - restart zookeeper

- name: Ensure kafka systemd file is present
  copy:
    src: kafka.service
    dest: /etc/systemd/system/kafka.service
  notify:
    - reload systemd
    - restart kafka

- meta: flush_handlers

- name: Ensure zookeeper is running and enabled
  service:
    name: zookeeper
    state: started
    enabled: yes

- name: Ensure kafka is running and enabled
  service:
    name: kafka
    state: started
    enabled: yes
