---

- name: reload systemd
  command: systemctl daemon-reload

- name: restart prometheus
  service:
    name: prometheus
    state: restarted

- name: stop prometheus
  service:
    name: prometheus
    state: stopped
