global:
  resolve_timeout: 10s
# The root route on which each incoming alert enters.
route:
  repeat_interval: 5s
  group_interval: 5s
  receiver: slack
  routes:

  - match:
      severity: critical
    receiver: slack
    continue: true
  - match:
      severity: critical
    receiver: jenkins

receivers:
- name: jenkins
  webhook_configs:
  - url: "http://admin:f62a2b7eb49458430f7529b8f1155a0f@192.168.201.10:8080/job/start_app/build?token=token"

- name: slack
  slack_configs:
  - api_url: https://hooks.slack.com/services/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
    channel: '#kubecon-demo'
    text: "<!channel>\nPython app stopped"
